### ISSUE TITLE
TypeError: $dialog.modal is not a function

### ISSUE THREAD

**Issue by longgeek** [summernote/angular-summernote#120]
In using summernote page, use the browser back or forward a page will throw the following exception, I do not know what causes, looks summernote problem。

TypeError: $dialog.modal is not a function
    at Object.ui.hideDialog (http://localhost:3001/bower_components/summernote/dist/summernote.js:1976:15)
    at destroy (http://localhost:3001/bower_components/summernote/dist/summernote.js:6380:10)
    at removeModule (http://localhost:3001/bower_components/summernote/dist/summernote.js:1668:18)
    at http://localhost:3001/bower_components/summernote/dist/summernote.js:1576:14
    at Array.forEach (native)
    at _destroy (http://localhost:3001/bower_components/summernote/dist/summernote.js:1575:43)
    at destroy (http://localhost:3001/bower_components/summernote/dist/summernote.js:1535:12)
    at invoke (http://localhost:3001/bower_components/summernote/dist/summernote.js:1708:33)
    at $.fn.extend.summernote (http://localhost:3001/bower_components/summernote/dist/summernote.js:1747:33)
    at HTMLDivElement.<anonymous> (http://localhost:3001/bower_components/angular-summernote/dist/angular-summernote.js:150:17)

**Comment by scne** [comment]
up

**Comment by bjaraujo** [comment]
Hi,

I am having similar problem. Why is this closed? Have you found a solution?

**Comment by silviotroia** [comment]
i solved add bootstrap library inside the project
`bower_components/bootstrap/dist/js/bootstrap.js`
