### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery'

### ISSUE THREAD

**Issue by monsieur-ricky** [summernote/angular-summernote#177]
Hi,

I'm trying to use angular-summernote in a Electron app, but i keep getting this error when i include summernote.js in my project:
> Uncaught Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\me\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at file:///C:/Users/me/projects/FO/dist/vendors/summernote/summernote.js:18:30
    at file:///C:/Users/me/projects/FO/dist/vendors/summernote/summernote.js:23:2

I'm using other jQuery plugins in this project without any problems.
Any ideas how to resolve this issue?

**Comment by RohanMohite** [comment]
Below solution worked for me.

Installing jquery in npm package to your local machine, type the below into your command line. You’ll notice a node_modules directory appear in your root where the package is now installed.

npm install jquery

And then add below line in your html file.
<script>window.jQuery = window.$ = module.exports</script>
